[package]
name = "kornia_rs"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.0"
vviz = {version = "0.3.0"}
turbojpeg = {version = "^0.3", features = ["image"]}
pyo3 = { version = "0.15.1", features = ["extension-module"] }

[dev-dependencies]
criterion = "0.3"
pprof = { version = "0.3", features = ["flamegraph"] }


[[bench]]
name = "my_benchmark"
harness = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "kornia_rs"
crate-type = ["cdylib", "lib"]
path = "src/lib.rs"
