[package]
name = "kornia-vlm"
description = "Vision Language Models in Rust"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
include = { workspace = true }
license = { workspace = true }
readme = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[dependencies]
candle-core = { version = "0.9.1" }
candle-transformers = { version = "0.9.1" }
candle-examples = "0.9.1"
candle-nn = { version = "0.9.1" }
hf-hub = "0.4.2"
kornia-image = { workspace = true }

kornia-tensor = { workspace = true }
kornia-io ={ workspace = true }
kornia-imgproc = { workspace = true }
log = "0.4"
serde_json = "1"
tokenizers = { version="0.21.1", features = ["http"] }
thiserror = "2"

candle-flash-attn = { version = "0.8.4" }  # Must use same candle_core
rand = "0.9.0"
terminal_size = "0.4.2"
reqwest = { version = "0.12.15", features = ["blocking"] }
image = "0.25.6"

[features]
cuda = ["candle-core/cuda", "candle-transformers/cuda", "candle-nn/cuda"]
