[package]
name = "kornia-vlm"
description = "Vision Language Models in Rust"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
include = { workspace = true }
license = { workspace = true }
readme = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[dependencies]
kornia-image = { workspace = true }

candle-core = { git = "https://github.com/huggingface/candle", version="0.8.4", features = ["cuda"] }
candle-nn = { git = "https://github.com/huggingface/candle", features = ["cuda"] }
candle-transformers = { version="0.8.4", features = ["cuda"] }
candle-flash-attn = { version = "0.8.4" }  # Must use same candle_core
hf-hub = "0.4.2"
tokenizers = { version="0.21.1", features = ["http"] }
rand = "0.9.0"
terminal_size = "0.4.2"
reqwest = { version = "0.12.15", features = ["blocking"] }
image = "0.25.6"
