[package]
name = "kornia-vlm"
description = "Vision Language Models in Rust"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
include = { workspace = true }
license = { workspace = true }
readme = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[dependencies]
log = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }

kornia-image = { workspace = true }
kornia-tensor = { workspace = true }
kornia-io = { workspace = true }
kornia-imgproc = { workspace = true }

candle-core = { workspace = true }
candle-transformers = { workspace = true }
candle-examples = { workspace = true, optional = true }
candle-nn = { workspace = true }
hf-hub = { workspace = true }
tokenizers = { workspace = true }

[dev-dependencies]
rand = "0.9.0"
# important: also inherit the CPU-only versions here
candle-core = { workspace = true }
candle-nn = { workspace = true }
candle-transformers = { workspace = true }


# candle-onnx = "0.9.1"
# ort = "1.16"     # or latest version
# ndarray = "0.15" # for easy tensor handling

[features]
default = []
cuda = ["candle-core/cuda", "candle-transformers/cuda", "candle-nn/cuda"]
debug = []
examples = ["dep:candle-examples"]                                        # opt-in path to use candle-examples
